- .github/workflows/blog-build-deploy.yml
Created PR to test out PR side of workflows.
> fix(workflows): update `app-name` for SWA app

- .biceps/_dns-zone.bicep
- .biceps/_static-web-app.bicep
- .biceps/main.bicep
- .github/lighthouse/lighthouse-config.js
- .github/lighthouse/lighthouseCommentMaker.js
- .github/lighthouse/lighthousesrc.json
- .github/workflows/blog-build-deploy.yml
Update PR validation to create new resources from biceps, and delete them once PR closed, and report lighthouse score, with placeholder to run end to end tests (to be implemented later).
> feat(workflows): create standalone resources for preview

- .github/workflows/blog-build-deploy.yml
Updated to use SWA preview environment.
> feat(workflows): use SWA preview environment correctly

- .github/workflows/blog-build-deploy.yml
- apps/blog/src/app/app.component.html
- apps/blog/src/app/app.component.spec.ts
- apps/blog/src/app/app.routes.ts
- apps/blog/src/app/pages/about-me.component.ts
- apps/blog/src/app/pages/landing.component.spec.ts
- apps/blog/src/app/pages/landing.component.ts
Trying out using `@defer` in landing page to load `about-me.component` and in root component to load footer.
> feat(blog): move about-me to landing page

- apps/blog/src/app/app.config.ts
- apps/blog/src/app/pages/about-me.component.spec.ts
- ng-features/blog-container/src/lib/pages/blog-entry/blog-entry.component.spec.ts
- ng-libs/ui-elements/package.json
- ng-libs/ui-elements/src/lib/article/article-nav/article-nav.component.html
- ng-libs/ui-elements/src/lib/article/article-nav/article-nav.component.spec.ts
- ng-libs/ui-elements/src/lib/article/article-nav/article-nav.component.ts
- ng-libs/ui-elements/src/lib/article/article.component.spec.ts
- ng-libs/ui-elements/src/lib/article/article.component.ts
- Updated navigation selection to unselect navigation elements when scrolling above blog.
- Added `Back to top` nav element when a navigation element is selected.
- Added animation to added/removed navigation elements.
> Fix up glob navigation elements

- .gitattributes
- .github/workflows/workflow-build-app.yml
- apps/blog/project.json
- apps/blog/src/robots/production/robots.txt
- apps/blog/src/robots/staging/robots.txt
> fix(blog): include `robots.txt` in root of application

- .github/workflows/blog-build-deploy.yml
- .github/workflows/workflow-build-app.yml
- .github/workflows/workflow-test-affected.yml
- apps/blog/project.json
- apps/blog/src/app/app.component.spec.ts
- apps/blog/src/robots/staging/robots.txt
Using correct string to check if workflow run on `main` branch. And minor tweak to blog app to trigger deployment pipeline.
> Update workflow and trigger deployment

- .github/ISSUE_TEMPLATE/something-went-wrong-🫣.md
Added bug issue template to improve process on generating issues.
> feat: add bug issue template

- README.md
- ng-libs/README.md
- ng-libs/services/README.md
- ng-libs/services/src/lib/pj-article-parser/README.md
> update links for documentation

- .github/ISSUE_TEMPLATE/eureka.yml
- .github/ISSUE_TEMPLATE/something-went-wrong.yml
> Add initial labels for issues

- .github/workflows/_workflow.jobs.infra.yml
- .github/workflows/_workflow.jobs.lint_test_build_affected.yml
- .github/workflows/blog-build-deploy.yml
- apps/blog/src/app/app.config.ts
- apps/blog/src/index.html
- ng-libs/styles/src/lib/styles/dark-theme.scss
- ng-libs/styles/src/lib/styles/light-theme.scss
- ng-libs/styles/src/lib/styles/mixins.scss
- ng-libs/styles/src/lib/styles/mixins/declare-block-classes.scss
- ng-libs/styles/src/lib/styles/mixins/generate-from-theme.scss
- ng-libs/styles/src/lib/styles/variables.scss
- package-lock.json
- package.json
Installed to use inputs, found it a bit challenging to get theming right.
Don't think it's done perfectly, but it serves its purpose for now... should possibly document it so that I don't forget wtf I did... hopefully get around to that.
Fixed up workflows:
- Updated condition check for closing staging deployment
- Updated labels for re-usable workflows in blog workflow, trying out just using icons to group the workflow jobs
- Added `is_affected` job to check if the current changes have affected the project requested to reduce usage of nx-cloud
> install @angular/material

- .github/ISSUE_TEMPLATE/requires-enlightenment.yml
- .github/lighthouse/lighthouse-report.parser.js
- .github/workflows/README.md
- .github/workflows/_workflow.jobs.clean_pull_request.yml
- .github/workflows/_workflow.jobs.infra.yml
- .github/workflows/_workflow.jobs.lint_test_build_affected.yml
- .github/workflows/_workflow.jobs.post_deploy.yml
- .github/workflows/_workflow.jobs.preparation.yml
- .github/workflows/blog-build-deploy.yml
- Moved clearing staging deployment to a re-usable workflow
- Fixed condition used for clearing staging deployment, used event name `pullrequest` instead of `pull_request`
- Added readme to `.github/workflows`
- Added comments to workflows to describe their purpose
- Added template for creating issue to improve documentation 
Resolves: #68
> Fix close staging deployment in workflow

- ts-libs/markdown-parser/README.md
- ts-libs/markdown-parser/src/lib/README.md
Updated links in `markdown-parser` docs
> chore(md-parser): update docs to link helper/reader fns

- .github/lighthouse/lighthouse-report.parser.js
- .github/workflows/_workflow.jobs.post_deploy.yml
Updated lighthouse report parser to add comment lines to summary for action.
- Pass in `core.summary` to lighthouse report parser
- Updated lighthouse report parser to use `addRaw` for each line of lighthouse report and finally `write` once done.
- Closes #74
After making changes to blog need to double check that the changes are effective.
> Output lighthouse report to summary

- .codecov.yml
Updated to try out `component_management`
> chore(.github): enable components for codecov

- apps/blog/src/app/components/header/header.component.ts
- apps/blog/src/index.html
Updated link or logo pre-load to use needed attributes.
Updated floating header to show as soon as top header is out of view.
<details>
Closes #105  and #86\
</details>
> Fix preload and floating header

- apps/blog/src/app/components/header/header.component.html
- apps/blog/src/app/components/header/header.component.ts
Used `mat-toolbar` to display floating header.
> feat(blog): update floating header using `mat-toolbar`

- README.md
Added `megalinter` badge in README.md
> chore: add linter badge to README.md

- apps/blog/src/app/components/header/header.component.html
- apps/blog/src/app/components/header/header.component.spec.ts
- apps/blog/src/app/components/header/header.component.ts
Decided that it does not bring enough value to warrant more tweaking.
<details>
Resolves #119
</details>
> feat(blog): remove floating header

- .github/workflows/_workflow.jobs.lint_test_build_affected.yml
- .github/workflows/ci_cd.yml
- .github/workflows/mega-linter.yml
Added job to check status of all jobs in CI/CD workflow, to have a single required job for branch permissions.
<details>
Fixes #125 
Going to use this PR for testing status check fails properly.
</details>
> feat(.github): add status check job for CI/CD

- ts-libs/md-parser/src/lib/parse-markdown.spec.ts
- ts-libs/md-parser/test-mds/quote.md
Mistakenly merged while test was ignored.
To prevent this mistake happening in future, the branch rules for `main` have been updated to require Megalinter to pass before merge is possible.
<details>
Related to #49
</details>
> fix(md-renderer): drop ignore for quote parsing spec

- .github/PULL_REQUEST_TEMPLATE.md
Updated pull request template.
- Removed comments in check list
- Slight formatting adjustments to try and make things easier
- Reworded `Optional Sections` to `Additional details`
> chore(.github): update pull request template

- ng-libs/md-renderer/package.json
- ng-libs/md-renderer/src/lib/components/md-code-block.component.spec.ts
- ng-libs/md-renderer/src/lib/components/md-code-block.component.ts
- ng-libs/md-renderer/src/lib/models/highlighted-code.ts
- ng-libs/md-renderer/src/lib/models/index.ts
- ng-libs/md-renderer/src/lib/services/code-highlight.service.spec.ts
- ng-libs/md-renderer/src/lib/services/code-highlight.service.ts
- ng-libs/md-renderer/src/lib/services/index.ts
- ng-libs/styles/src/lib/styles/dark-theme.scss
- ng-libs/styles/src/lib/styles/light-theme.scss
- package-lock.json
- package.json
Included code highlighting for `md-code-block` component, using `highlight.js` package.
Styles imported from package into themes, and basic languages registered for use.
<details>
Closes #110
</details>
> feat(md-renderer): add code highlighting

- apps/blog/src/app/app.config.ts
- apps/blog/src/app/pages/about-me/about-me.component.scss
- apps/blog/src/app/pages/about-me/about-me.component.spec.ts
- apps/blog/src/app/pages/about-me/about-me.component.ts
- apps/blog/src/assets/docs/about-me.md
Updated `about-me` page to use markdown file.
> feat(blog): use markdown file for `about-me`

- apps/blog/src/assets/docs/development-notes/README.md
Updated `development-notes` with progress on week 1
> chore(blog): update development-notes week 1 (1/3)

- .github/lighthouse/lighthouse-report.parser.js
- .github/workflows/_workflow.jobs.cd.yml
- .github/workflows/ci_cd.yml
This pull request includes significant updates to the `.github` workflows and the `lighthouse-report.parser.js` file to improve the CI/CD process and enhance the Lighthouse report generation. The most important changes include restructuring the CI/CD workflow, enhancing the Lighthouse report parser, and updating the build and deploy job configurations.
* **Restructured CI/CD Workflow**:
* Consolidated the `build_deploy_blog` job into a more flexible `build_deploy` job using a matrix strategy to handle multiple projects. [[1]](diffhunk://#diff-c80d54cb778b5196ee7b73e152870cac313eed095f65886e3f15247cdc900d1aL32-R152) [[2]](diffhunk://#diff-c80d54cb778b5196ee7b73e152870cac313eed095f65886e3f15247cdc900d1aL62-R170)
* Added a new `audit_deployed` job to handle the auditing process separately …
> feat(.github): use strategy for deployment

- .biceps/_swa-rg.bicep
- .github/workflows/ci_cd.yml
This pull request includes updates to the infrastructure and CI/CD pipeline configurations. The key changes involve adding a new resource for custom domains in the Bicep file and modifying the deployment behavior in the GitHub Actions workflow.
Infrastructure updates:
* [`.biceps/_swa-rg.bicep`](diffhunk://#diff-68d0b80b45680ca4fe6fb5605499c397ed2e5e76fe628d9c4dd78cf7d072d56cR51-R55): Added a new resource `customDomain` to manage custom domains for static web apps. (`[.biceps/_swa-rg.bicepR51-R55](diffhunk://#diff-68d0b80b45680ca4fe6fb5605499c397ed2e5e76fe628d9c4dd78cf7d072d56cR51-R55)`)
CI/CD pipeline updates:
* [`.github/workflows/ci_cd.yml`](diffhunk://#diff-c80d54cb778b5196ee7b73e152870cac313eed095f65886e3f15247cdc900d1aL45-R45): Changed the `force_deployment` parameter from `false` …
> fix(.biceps): add `customDomain` for deployed SWA

- .biceps/_static-web-app.bicep
- .biceps/_swa-rg.bicep
- .github/workflows/ci_cd.yml
- .trivyignore
Decided to leave custom domain as a manual step for now. Keeps failing with error `CNAME Record is invalid.  Please ensure the CNAME record has been created.`, while it has been created.
So, leaving it as a manual step in the process, fortunately only needed once for creation of the SWA.
<details>
#169 
</details>
> chore: remove attempt for registering custom domain

- .codecov.yml
Updated codecov configuration to include `tasks-to-do` coverage as a component.
<details>
</details>
> chore(ttd): include project in codecov

- .run/pre-push_check.run.xml
- ng-libs/task-management/src/lib/components/index.ts
- ng-libs/task-management/src/lib/components/task-view.component.spec.ts
- ng-libs/task-management/src/lib/components/task-view.component.ts
- ng-libs/task-management/src/lib/models/get-tasks-query.ts
- ng-libs/task-management/src/lib/models/index.ts
- ng-libs/task-management/src/lib/pages/tasks-display.component.ts
- ng-libs/task-management/src/lib/services/tasks-data.service.ts
- ng-libs/task-management/src/lib/task-management/task-management.component.html
This pull request includes several changes to the task management library, focusing on the addition of a new component, removal of unnecessary code, and updates to existing components to integrate the new component.
* [`ng-libs/task-management/src/lib/components/task-view.component.ts`](diffhunk://#diff-6e020ee91cf5137699de4c3eb47604a2036004a739c1df96ca5cb37c83cc72e7R1-R25): Added a new `TaskViewComponent` to display task details.
* [`ng-libs/task-management/src/lib/components/task-view.component.spec.ts`](diffhunk://#diff-123e37edc61cbdc963f47292fadd9d01b9114ea132eeb6cd33b6c00aa48b6669R1-R22): Added unit tests for the new `TaskViewComponent`.
* [`ng-libs/task-management/src/lib/components/index.ts`](diffhunk://#diff-6b981f8d4bab7f4149ee80e107b64ef83d66f5d78f9d7a12ff4ea992073dd34fR1): …
> feat(task-management): create component to display task details

- .codecov.yml
- README.md
Altered codecov configuration to ignore removed project. And updated badge for codecov.
> chore: update codecov configuration

- apps/blog/src/app/primary.component.ts
Removed logging of animation context.
> chore(blog): remove animation logging

- README.md
Updated badges in root README, and added label deployment workflow badge.
> chore: tweak README badges

- .github/PULL_REQUEST_TEMPLATE.md
- .github/lighthouse/lighthouse-report.parser.js
- .github/workflows/_workflow.jobs.cd.yml
This pull request includes changes to the `.github` directory, specifically to the pull request template and the Lighthouse report parser. The most important changes involve reordering sections in the pull request template and modifying the Lighthouse summary type definition.
Changes to the pull request template:
* [`.github/PULL_REQUEST_TEMPLATE.md`](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35L3-R11): Reordered the "Details" section to be placed after the checklist for better readability.
Changes to the Lighthouse report parser:
* [`.github/lighthouse/lighthouse-report.parser.js`](diffhunk://#diff-8787107ebf392520b169a2fd9643c1341631b33c81d802b6504fe94008cf3f70L46-R54): Removed 'pwa' from the `LighthouseSummary` typedef and commented out the …
> chore(.github): minor changes for lighthouse reports

- apps/bb-score/src/app/games/game-create/game-create.component.spec.ts
- apps/bb-score/src/app/games/game-create/game-create.component.ts
- apps/bb-score/src/app/games/game-list/game-list.component.spec.ts
- apps/bb-score/src/app/games/game-list/game-list.component.ts
- apps/bb-score/src/app/games/games.routes.ts
- Removed the GameCreateComponent route from gamesRoutes to streamline navigation.
- Updated GameCreateComponent to utilize MatBottomSheet for creating games, enhancing user experience.
- Modified GameListComponent to open the GameCreateComponent in a bottom sheet when the "New Game" button is clicked, improving the flow of game management.
- Added tests for the new bottom sheet functionality in both GameCreateComponent and GameListComponent to ensure proper behavior.
feat(bb-score): enhance game creation functionality
- Added a subtitle to the GameCreateComponent to display the number of games created.
- Introduced a new button to allow users to add another game without closing the form.
- Updated the onSubmit method to reset the form while retaining the league and adjusting the date for …
> feat(bb-score): refactor game creation to allow creating multiple

- apps/bb-score/src/app/games/game-list/game-list.component.spec.ts
- apps/bb-score/src/app/games/game-list/game-list.component.ts
- apps/bb-score/src/app/games/game.service.spec.ts
- apps/bb-score/src/app/games/game.service.ts
- Refactored GameService to utilize localStorage for persistent game data management, including loading and saving games.
- Updated tests in game.service.spec.ts to cover scenarios for initializing, creating, updating, and deleting games, ensuring localStorage is correctly updated.
- Modified GameListComponent to reflect changes in game retrieval logic, improving the user experience when displaying games.
- Enhanced test coverage for GameListComponent to ensure proper interaction with the updated GameService.
<details>
</details>
> feat(bb-score): enhance GameService and tests for game management

- apps/bb-score/src/app/app.component.html
- apps/bb-score/src/app/app.component.spec.ts
- apps/bb-score/src/app/app.component.ts
- apps/bb-score/src/app/core/components/update-toast/update-toast.component.ts
- apps/bb-score/src/app/core/services/sw-update.service.spec.ts
- apps/bb-score/src/app/core/services/sw-update.service.ts
- Introduced a new `UpdateToastComponent` to notify users when a new version of the application is available.
- Updated `app.component.html` to include the `app-update-toast` component for displaying update notifications.
- Modified `app.component.ts` to import the `UpdateToastComponent`.
- Enhanced unit tests for `AppComponent` to mock the `UpdateToastComponent` during testing.
- Created `SwUpdateService` to manage service worker updates and notify the application of version changes.
- Added tests for `SwUpdateService` to ensure correct behavior when updates are available and activated.
<details>
</details>
> feat(bb-score): add update toast component for version notifications

- apps/bb-score/src/app/app.component.html
- apps/bb-score/src/app/app.component.ts
- apps/bb-score/src/app/core/components/update-toast/update-toast.component.ts
- apps/bb-score/src/app/games/game-create/game-create.component.ts
- Refactored the GameCreateComponent to enhance the layout by replacing the mat-card structure with a more semantic header and form layout.
- Improved styling for the form fields and button container to ensure better responsiveness and user experience.
- Maintained existing functionality while streamlining the component's structure for clarity and maintainability.
feat(bb-score): hide sidenav when loaded with mobile
Component to be used for toast, rendered directly. Updated to only display content when in a snackbar, and pass in needed value to know that it is in a snackbar when opening the snackbar.
Testing of update to be done...
<details>
</details>
> fix(bb-score): update snack bar for version update

- apps/bb-score/src/app/games/lineup-edit/lineup-edit.component.ts
- apps/bb-score/src/app/games/lineup-edit/player-select/player-select.component.ts
- Display number input for bench players
- Adjusted inputs for players in lineup to try and streamline process
- Moved add player button to title (including adding new title)
<details>
> Updated display of inputs
> Number requested for bench players
> Font size for header title updated
</details>
> fix(bb-score): display number for bench players

- apps/bb-score/src/app/games/game-score/game-score-edit.component.ts
- apps/bb-score/src/app/games/game-score/games-score.routes.ts
- apps/bb-score/src/app/games/game-score/scoring/README.md
- apps/bb-score/src/app/games/game-score/scoring/batting.component.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-action.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-snapshot.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-state.ts
- apps/bb-score/src/app/games/game-score/scoring/models/index.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.routes.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.service.spec.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.service.ts
- apps/bb-score/src/app/games/game-score/scoring/status.component.ts
- apps/bb-score/src/app/games/game.service.spec.ts
- apps/bb-score/src/app/games/game.service.ts
- apps/bb-score/src/app/games/models/game.ts
Created scoring section to be used for scoring games.
Added `ScoringService` to be used to generate and append snapshots to the game.
Updated `GameService` to be able to append snapshots.
After this, need to continue updating `ScoringService` to handle actions, and update display components to render state correctly.
> feat(bb-score): start framework for scoring

- apps/bb-score/src/app/games/game-score/game-score-edit.component.ts
- apps/bb-score/src/app/games/game-score/scoring/bases-status.component.ts
- apps/bb-score/src/app/games/game-score/scoring/field-status.component.ts
- apps/bb-score/src/app/games/game-score/scoring/fielding.component.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-snapshot.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-state.ts
- apps/bb-score/src/app/games/game-score/scoring/models/scoring-player.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.routes.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.service.spec.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.service.ts
- apps/bb-score/src/app/games/game-score/scoring/status.component.ts
- apps/bb-score/src/app/games/game.service.spec.ts
This pull request introduces a scoring feature for games. It includes an initial implementation to calculate and display the score.
<details>
N/A
N/A
1. Initiate a game.
2. Verify that the scoring system computes and displays scores as expected.
</details>
> Add scoring feature for games

- apps/bb-score/src/app/games/game-score/game-score-edit.component.ts
- apps/bb-score/src/app/games/game-score/scoring/batting.component.ts
- apps/bb-score/src/app/games/game-score/scoring/fielding.component.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-action.ts
- apps/bb-score/src/app/games/game-score/scoring/models/game-snapshot.ts
- apps/bb-score/src/app/games/game-score/scoring/scoring.service.ts
Initial implementation of the hitting mechanics related to scoring in the system. Further refinements and additional logic will be added in future updates.
<details>
</details>
> feat(bb-score) start implementing hitting for scoring

- .jscpd.json
- apps/bb-score/src/app/app.component.scss
- apps/bb-score/src/app/components/game-actions.component.ts
- apps/bb-score/src/app/components/game-play.component.ts
- apps/bb-score/src/app/components/team.component.ts
- apps/bb-score/src/app/models/index.ts
- apps/bb-score/src/app/signal-store/game-store.ts
Added button to record a ball pitched and updated state management to partially handle it, still has runner management to be implemented.
> feat(bb-score): update to partially handle balls

- apps/bb-score/src/app/components/game-actions.component.ts
- apps/bb-score/src/app/components/game-play.component.ts
- apps/bb-score/src/app/components/team.component.ts
- apps/bb-score/src/app/models/index.ts
- apps/bb-score/src/app/signal-store/create-game.ts
- apps/bb-score/src/app/signal-store/game-store.ts
- Updated to handle walks and runner progression.
- Updated to handle balks and hit-by-pitch
- Started handling batter hits and fouls
> feat(bb-score): extend pitch handling
