peterjokumsen/peterjokumsen-nx-workspace

.github/workflows/blog-build-deploy.yml

Removed `--yes` parameter from delete command, should resolve error on workflow run after closing PR.

fix(workflows): remove unknown parameter for delete command

---

apps/blog/src/app/components/about-me/about-me.component.ts
ng-libs/styles/src/lib/styles/global.scss
ng-libs/ui-elements/package.json
ng-libs/ui-elements/src/lib/article/pipes/index.ts
ng-libs/ui-elements/src/lib/article/pipes/split-to-anchor.pipe.spec.ts
ng-libs/ui-elements/src/lib/article/pipes/split-to-anchor.pipe.ts
ng-libs/ui-elements/src/lib/article/section/container/article-section.component.html
ng-libs/ui-elements/src/lib/article/section/container/article-section.component.spec.ts
ng-libs/ui-elements/src/lib/article/section/container/article-section.component.ts

Resolves: #28 
Updated to replace markdown link `[title](url)` format in content, into anchor tags.

render anchor in article section

---

.codecov.yml
ts-libs/markdown-parser/src/lib/_models/index.ts
ts-libs/markdown-parser/src/lib/_models/matched-content.ts
ts-libs/markdown-parser/src/lib/helper-fns/README.md
ts-libs/markdown-parser/src/lib/helper-fns/index.ts
ts-libs/markdown-parser/src/lib/helper-fns/line-has.spec.ts
ts-libs/markdown-parser/src/lib/helper-fns/line-has.ts
ts-libs/markdown-parser/src/lib/helper-fns/regex-patterns.ts
ts-libs/markdown-parser/src/lib/helper-fns/split-rich-content.spec.ts
ts-libs/markdown-parser/src/lib/helper-fns/split-rich-content.ts
ts-libs/markdown-parser/src/lib/models/index.ts
ts-libs/markdown-parser/src/lib/models/markdown-content-type.ts
ts-libs/markdown-parser/src/lib/models/markdown-content.ts
ts-libs/markdown-parser/src/lib/models/rich-content-type.ts
ts-libs/markdown-parser/src/lib/parse-markdown.spec.ts
ts-libs/markdown-parser/src/lib/reader-fns/README.md
ts-libs/markdown-parser/src/lib/reader-fns/match-rich-content.spec.ts
ts-libs/markdown-parser/src/lib/reader-fns/match-rich-content.ts
ts-libs/markdown-parser/src/lib/reader-fns/read-paragraph.spec.ts
ts-libs/markdown-parser/src/lib/reader-fns/read-paragraph.ts
ts-libs/markdown-parser/src/lib/test-mds/image-and-link.md
ts-libs/markdown-parser/src/lib/test-mds/image-only.md
ts-libs/markdown-parser/src/lib/test-mds/link-only.md
ts-libs/markdown-parser/src/lib/test-mds/link-with-image.md

Still a ways to go with this, but can give a whirl at a renderer for these objects soon and possibly reset how pages are shown.

extend markdown-parser to consume images and links

---

.github/workflows/ci_cd.yml
apps/blog/src/app/app.component.html
apps/blog/src/app/app.component.spec.ts
apps/blog/src/app/app.component.ts
apps/blog/src/app/app.config.ts
apps/blog/src/app/components/change-history/change-history.component.html
apps/blog/src/app/components/change-history/change-history.component.ts
apps/blog/src/app/components/footer/footer.component.spec.ts
apps/blog/src/app/components/footer/footer.component.ts
apps/blog/src/app/components/header/header.component.html
apps/blog/src/app/components/header/header.component.spec.ts
apps/blog/src/app/components/header/header.component.ts
apps/blog/src/app/components/header/index.ts
ng-libs/services/src/lib/pj-article-parser/pj-article-parser.service.ts
ng-libs/ui-elements/src/lib/article/article-nav/article-nav.component.html
ng-libs/ui-elements/src/lib/router-nav/models/flex-overrides.ts
ng-libs/ui-elements/src/lib/router-nav/models/index.ts
ng-libs/ui-elements/src/lib/router-nav/router-nav.component.spec.ts
ng-libs/ui-elements/src/lib/router-nav/router-nav.component.ts

Updated to show header navigation throughout the component.
- Updated router-nav component to allow for override the flex classes used, using `[ngClass]` to allow TailWind to include the necessary classes used.
- Created new header component in `blog` to render header, and updated it to show secondary header when screen goes past page introduction. Acts as a button that when clicked shows navigation for the site.
- Moved theme toggle component into router-nav to enable switching theme in header. Although initial size now over warning, but will create a new issue to try and minimize the initial build size.
<details>
Closes #72
</details>

Show secondary header after introduction

---

README.md

Updated workflow badge in core README.md
Rename of workflow file broke the badge. With fix, moved it to the top of the file.

Update badge for workflow in README

---

apps/blog/src/app/app.config.ts
apps/blog/src/app/app.routes.ts
apps/blog/src/app/splash.component.spec.ts
apps/blog/src/app/splash.component.ts

To try and fix flash of dark to light theme after primary component loaded, updated splash component to set theme.
- Moved providers into `app.config.ts` to allow setting theme.
- Updated splash component to set first available theme.
- Looks like moving the providers around helped with initial load bundle size.
<details>
Related to #67 #86
Plan to test in PR workflow (Should be able to check on lighthouse reports)
</details>

Set theme in splash component

---

.github/workflows/_workflow.jobs.lint_test_build_affected.yml

Adjusted bash script to only checkout `main` when `rev-parse` command is falsy.
-
<details>
</details>

fix(.github): adjust git commands to checkout `main`

---

ng-libs/md-renderer/src/lib/components/index.ts
ng-libs/md-renderer/src/lib/components/md-code.component.spec.ts
ng-libs/md-renderer/src/lib/components/md-code.component.ts
ng-libs/md-renderer/src/lib/filter-content-types.ts
ng-libs/md-renderer/src/lib/md-components.module.ts
ng-libs/md-renderer/src/lib/services/md-component-map.service.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.spec.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.ts
ts-libs/md-parser/src/lib/parse-markdown.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-paragraph.ts
ts-libs/md-parser/src/lib/test-mds/inline-code.md

Updated `md-parser` and `md-renderer` to handle `'code'` elements

Update parser and renderer to handle inline code

---

ng-libs/md-renderer/src/lib/components/md-code.component.ts
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.html
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.scss
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.spec.ts
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.ts
ng-libs/md-renderer/src/lib/toc/index.ts
ng-libs/md-renderer/src/lib/toc/mobile-toc.component.spec.ts
ng-libs/md-renderer/src/lib/toc/mobile-toc.component.ts
ng-libs/md-renderer/src/lib/toc/table-of-contents.component.html
ng-libs/md-renderer/src/lib/toc/table-of-contents.component.scss
ng-libs/md-renderer/src/lib/toc/table-of-contents.component.spec.ts
ng-libs/md-renderer/src/lib/toc/table-of-contents.component.ts

Created `MobileTocComponent`, rendered in `md-renderer` component, with position absolute to prevent element width from affecting width of content.
Fixes #100

Update markdown navigation for mobile

---

apps/blog/src/app/pages/about-me/about-me.component.ts
ng-libs/md-renderer/src/lib/components/index.ts
ng-libs/md-renderer/src/lib/components/md-code-block.component.spec.ts
ng-libs/md-renderer/src/lib/components/md-code-block.component.ts
ng-libs/md-renderer/src/lib/components/md-code.component.ts
ng-libs/md-renderer/src/lib/filter-content-types.ts
ng-libs/md-renderer/src/lib/md-components.module.ts
ng-libs/md-renderer/src/lib/services/md-component-map.service.ts
ts-libs/md-parser/src/lib/helper-fns/get-section-content-type.spec.ts
ts-libs/md-parser/src/lib/helper-fns/get-section-content-type.ts
ts-libs/md-parser/src/lib/parse-markdown.spec.ts
ts-libs/md-parser/src/lib/reader-fns/generate-markdown-sections.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-code-block.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-code-block.ts
ts-libs/md-parser/src/lib/reader-fns/read-section.ts
ts-libs/md-parser/src/lib/test-mds/code-block.md
ts-libs/ts-md-models/src/lib/markdown-content.ts

- Updated `md-parser` to read code blocks from markdown.
- Updated `md-renderer` to display parsed code blocks.
- Fixed `md-renderer` display of code elements.
<details>
Closes #45
</details>

Update parser and renderer to handle code blocks

---

.github/workflows/_workflow.jobs.post_deploy.yml

Added `id-token: write` permission for post_deploy workflow, to allow for authenticating with Azure.

fix(.github): include `id-token` permission for post_deploy

---

ng-libs/md-renderer/src/lib/components/md-code-block.component.ts
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.html
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.scss

Set container for markdown content to 100%, use overflow-x for code-block content to prevent scroll.

fix(md-renderer): improve display for mobile devices

---

.github/workflows/_workflow.jobs.clean_pull_request.yml
.github/workflows/_workflow.jobs.post_deploy.yml

Set `id-token: write` in clean up re-usable workflow. Incorrectly set in post deploy workflow before this.

fix(.github): set `id-token` in correct workflow

---

package.json
ts-libs/md-parser/src/lib/helper-fns/get-section-content-type.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.spec.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.ts
ts-libs/md-parser/src/lib/parse-markdown.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-commented-block.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-commented-block.ts
ts-libs/md-parser/src/lib/reader-fns/read-section.ts
ts-libs/md-parser/test-mds/commented.md
ts-libs/ts-md-models/src/lib/markdown-content-type.ts
ts-libs/ts-md-models/src/lib/markdown-content.ts
ts-libs/ts-md-models/src/lib/md-model-check.spec.ts
ts-libs/ts-md-models/src/lib/section-content-type.ts

Parse comment blocks to an element with type `commented`

feat(md-parser): parse comment blocks

---

ng-libs/md-renderer/src/lib/components/index.ts
ng-libs/md-renderer/src/lib/components/md-commented.component.spec.ts
ng-libs/md-renderer/src/lib/components/md-commented.component.ts
ng-libs/md-renderer/src/lib/directives/md-content-injection.directive.ts
ng-libs/md-renderer/src/lib/filter-content-types.ts
ng-libs/md-renderer/src/lib/md-components.module.ts
ng-libs/md-renderer/src/lib/md-renderer/md-renderer.component.ts
ng-libs/md-renderer/src/lib/services/md-component-map.service.ts

Update renderer to ignore markdown elements with type of `commented`.

feat(md-renderer): handle `commented` markdown element

---

ng-libs/md-renderer/src/lib/components/md-code-block.component.ts

Updated style for `code-block` component, to use `auto` for overflow. To use scroll when content greater than current width, otherwise no scrollbar.
<details>
Fixes #120
</details>

fix(md-renderer): update overflow for code-block

---

ts-libs/ts-md-models/src/lib/markdown-content.ts
ts-libs/ts-md-models/src/lib/md-model-check.spec.ts

- Renamed `content` to `paragraphs`
- Added an option `indent` property... against my better judgement but keeping with the `indent` added to other models
> Because quotes can be indented, although I am not prepared to implement that as yet... will add an issue to hopefully get around to it.
<details>
Working on #49
</details>

feat(ts-md-models): reword properties for `quote` model

---

ts-libs/ts-md-models/src/lib/markdown-content.ts

- Enabled to allow `horizontal-rule` type
<details>
Worked on #49
</details>

fix(ts-md-models): extend `quote` `paragraphs` property

---

ts-libs/md-parser/src/lib/helper-fns/get-section-content-type.spec.ts
ts-libs/md-parser/src/lib/helper-fns/get-section-content-type.ts
ts-libs/md-parser/src/lib/parse-markdown.spec.ts
ts-libs/md-parser/src/lib/reader-fns/generate-markdown-sections.ts
ts-libs/md-parser/src/lib/reader-fns/read-quote.spec.ts
ts-libs/md-parser/src/lib/reader-fns/read-quote.ts
ts-libs/md-parser/src/lib/reader-fns/read-section.ts
ts-libs/md-parser/test-mds/quote.md

- Added `readQuote` to consume all consecutive quote elements
- Updated readers to use `readQuote`
<details>
Work on #49
</details>

feat(md-renderer): read `quote` elements from markdown

---

ts-libs/ts-md-models/src/lib/markdown-content.ts

Added optional `placement` property to image model, with string literal values of `'begin' | 'center' | 'end' | 'full'`.
<details>
Related to #32 
</details>

feat(ts-md-models): add `placement` property for image

---

ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.spec.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.ts
ts-libs/ts-md-models/src/lib/image-placement-type.ts
ts-libs/ts-md-models/src/lib/index.ts
ts-libs/ts-md-models/src/lib/markdown-content.ts

Updated parser to resolve image with URL using query parameter containing `placement=x` to use `x` as placement.
<details>
Relates to #32 
</details>

feat(md-parser): consume placement from query parameter in image URL

---

ng-libs/services/src/lib/pj-markdown-client/services/markdown-parser.service.spec.ts
ng-libs/services/src/lib/pj-markdown-client/services/markdown-parser.service.ts

After attempting to use `PjMarkdownClient`, found that images with `-` in filename are not correctly updated.
Updated regular expression used to adjust paths for images.

fix(ng-services): improve image path resolution for markdown

---

apps/blog/project.json

Updated `staging` build configuration (used for deployment in CI/CD workflow) to create service worker to prevent console error in lighthouse reports.
<details>
Resolves #61
</details>

fix(blog): update `staging` configuration to generate service worker

---

apps/blog/src/app/animations.ts
apps/blog/src/app/primary.component.html
apps/blog/src/app/primary.component.spec.ts
apps/blog/src/app/primary.component.ts

Updated `primary` component to perform animations on routing navigation changes.
For now just have a slide in animation, should be able to expand on this in the future.
Used [Angular tutorial](https://v17.angular.io/guide/route-animations) as an extremely helpful guide.
<details>
Closes #139 
</details>

feat(blog): add route navigation animation

---

apps/blog/src/app/primary.component.spec.ts
apps/blog/src/app/primary.component.ts

Update logic for router animation, when no previous animation applied will not animate. 
<details>
Fixes #149
</details>

fix(blog): only use router animation after initial load

---

ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.spec.ts
ts-libs/md-parser/src/lib/helper-fns/provide-regex-tools.ts
ts-libs/md-parser/src/lib/parse-markdown.spec.ts
ts-libs/md-parser/test-mds/inline-code.md

Resolve regular expression for reading `code` elements to be less greedy.
<details>
Resolves #154
</details>

fix(md-parser): update `code` parsing

---

.biceps/_dns-zone.bicep
.biceps/_swa-rg.bicep
.github/workflows/_workflow.jobs.cd.yml
.github/workflows/ci_cd.yml

Updated DNS deployment, to create CNAME record set in primary DNS Zone. Using hostname of deployed SWA.
Also updated CI/CD workflow, found that CD process waits for deployment to be ready when deployment not done, which could end up being a rather long wait.
DNS configuration updates:
* [`.biceps/_dns-zone.bicep`](diffhunk://#diff-16c50c8a5da284aefc297d1e1062525ae07df8dd98f718af6ab5a1d479f92cfdL7-R20): Changed the parameter from `targetResourceId` to `targetHostName` and updated the resource type from `A` to `CNAME`. (`[.biceps/_dns-zone.bicepL7-R20](diffhunk://#diff-16c50c8a5da284aefc297d1e1062525ae07df8dd98f718af6ab5a1d479f92cfdL7-R20))
* [`.biceps/_swa-rg.bicep`](diffhunk://#diff-68d0b80b45680ca4fe6fb5605499c397ed2e5e76fe628d9c4dd78cf7d072d56cL47-R47): Updated the module parameters to …

fix(.bicep): replace `A` record with `CNAME` for DNS

---

apps/tasks-to-do/src/index.html

Updated title for application, also using PR as a test of the workflows. Expecting:
- `ttd` deployed
- `blog` **not** deployed

chore(ttd): set title for project

---

.github/workflows/_workflow.jobs.cd.yml
.github/workflows/_workflow.jobs.ci.yml
.github/workflows/ci_cd.yml

Moved step to check if project is affected by changes from CD workflow into CI workflow. Checking this before any checkout in CD process allows for quicker skip when project is not affected.
The CI workflow outputs all affected applications as a comma-separated string. And passes this output into CD process.
CD process has a new job which checks for the project name in the new `affected_projects` input from CI process. The build and deploy job depends on this new job, and will be skipped if the job failed to find the project.
* [`.github/workflows/_workflow.jobs.cd.yml`](diffhunk://#diff-5d2d5523aa609da0f4aca508e5679ebb493f141329d1fd0dd7ff55b31cc840cfR21-R24): Added a new input `affected_projects` and updated the `check_affected` job to determine if a project is affected by the latest …

feat(.github): get affected projects when testing

---

.cspell.json
ng-libs/loading-indicator/.eslintrc.json
ng-libs/loading-indicator/README.md
ng-libs/loading-indicator/jest.config.ts
ng-libs/loading-indicator/ng-package.json
ng-libs/loading-indicator/package.json
ng-libs/loading-indicator/project.json
ng-libs/loading-indicator/src/index.ts
ng-libs/loading-indicator/src/lib/loading-indicator.component.spec.ts
ng-libs/loading-indicator/src/lib/loading-indicator.component.ts
ng-libs/loading-indicator/src/lib/loading.service.spec.ts
ng-libs/loading-indicator/src/lib/loading.service.ts
ng-libs/loading-indicator/src/lib/provide-loading-indicator.spec.ts
ng-libs/loading-indicator/src/lib/provide-loading-indicator.ts
ng-libs/loading-indicator/src/test-setup.ts
ng-libs/loading-indicator/tsconfig.json
ng-libs/loading-indicator/tsconfig.lib.json
ng-libs/loading-indicator/tsconfig.lib.prod.json
ng-libs/loading-indicator/tsconfig.spec.json
ng-libs/task-management/package.json
ng-libs/task-management/src/lib/lib.routes.ts
ng-libs/task-management/src/lib/services/tasks-data.service.spec.ts
ng-libs/task-management/src/lib/services/tasks-data.service.ts
ng-libs/task-management/src/lib/task-management/task-management.component.html
ng-libs/task-management/src/lib/task-management/task-management.component.spec.ts
ng-libs/task-management/src/lib/task-management/task-management.component.ts
tsconfig.base.json

Created `loading-indicator` library, which has `pj-loading-indicator` component and `LoadingService`. When calling `startLoading` function in `LoadingService`, will display progress spinner and after calling `completeLoading` function, will hide progress spinner.

feat(ttd): add loading indicator

---

ng-libs/md-renderer/src/lib/components/md-link.component.spec.ts
ng-libs/md-renderer/src/lib/components/md-link.component.ts
ng-libs/md-renderer/src/lib/components/md-quote-block.component.ts

This pull request includes several updates to the `MdLinkComponent` in the `ng-libs/md-renderer` library, focusing on renaming methods, updating imports, and enhancing content handling. The changes also include a minor style update to the `MdQuoteBlockComponent`.
Key changes:
* Renamed the `anchor` method to `currentAnchor` in `ng-libs/md-renderer/src/lib/components/md-link.component.ts` and updated all references in the corresponding test file `md-link.component.spec.ts`. [[1]](diffhunk://#diff-8310215a0f87e56ad89473bed64c118c38f179c5c018959aec18e1b081096d69L95-R95) [[2]](diffhunk://#diff-8310215a0f87e56ad89473bed64c118c38f179c5c018959aec18e1b081096d69L116-R116) [[3]](diffhunk://#diff-8310215a0f87e56ad89473bed64c118c38f179c5c018959aec18e1b081096d69L133-R142) …

fix(md-renderer): update display of link and quote block

---

.github/lighthouse/lighthouse-report.parser.js
.github/workflows/_workflow.jobs.cd.yml
.github/workflows/deploy-bullet-journal.yml

This pull request includes several changes to enhance the Lighthouse report parser and update workflow configurations. The most important changes are summarized below:
Enhancements to Lighthouse report parser:
* Added a new property `projectName` to the `LighthouseOutputs` typedef and updated related functions to include this new property. (`.github/lighthouse/lighthouse-report.parser.js`) [[1]](diffhunk://#diff-8787107ebf392520b169a2fd9643c1341631b33c81d802b6504fe94008cf3f70R23) [[2]](diffhunk://#diff-8787107ebf392520b169a2fd9643c1341631b33c81d802b6504fe94008cf3f70L103-R107) [[3]](diffhunk://#diff-8787107ebf392520b169a2fd9643c1341631b33c81d802b6504fe94008cf3f70L118-R122) [[4]](diffhunk://#diff-8787107ebf392520b169a2fd9643c1341631b33c81d802b6504fe94008cf3f70R145)
* Re-enabled the 'PWA' …

chore(.github): update workflow

---

apps/bb-score/src/app/teams/team-detail/team-detail.component.ts
apps/bb-score/src/app/teams/teams-list/teams-list.component.ts

- `apps/bb-score/src/app/teams/team-detail/team-detail.component.ts`
- `apps/bb-score/src/app/teams/teams-list/teams-list.component.ts`
- Updated the color of the text stating that there are no teams and no players to `var(--mat-sys-on-surface)`.
This will make the text readable in light and dark mode.
- Update the text for no teams, to be in two paragraphs, one below the other. This offers a better reading experience to the user.
https://github.com/peterjokumsen/peterjokumsen-nx-workspace/issues/206
1. checkout this branch
2. run `pnpm i`
3. run `npm run serve:bb-score`
4. navigate to [http://localhost:4200/teams](http://localhost:4200/teams)
1. note that the `no teams` text is easily readable in light and dark mode
5. click on the blue `+` button to create a new team
6. fill in any …

fix(bb-score): make no teams and -players text lighter

---

apps/bb-score/src/app/games/lineup-edit/lineup-edit.component.ts
apps/bb-score/src/app/games/lineup-edit/lineup.service.spec.ts
apps/bb-score/src/app/games/lineup-edit/lineup.service.ts
apps/bb-score/src/app/games/lineup-edit/player-select/player-select.component.html
apps/bb-score/src/app/games/lineup-edit/player-select/player-select.component.ts

- Updated player number placeholder to `#`
- Created `LineupService` to define positions and centralize positions already in use
- Updated `LineupEditComponent` to call `updateDisabledPositions` when starters updated
- Updated `PlayerSelectComponent` to disable position options that are already in use, except for the current player's position
<details>
</details>

feat(bb-score): disable used positions for lineup

---

apps/bb-score/src/app/core/components/update-toast/update-toast.component.ts
apps/bb-score/src/app/core/models/index.ts
apps/bb-score/src/app/core/models/update-status.ts
apps/bb-score/src/app/core/services/sw-update.service.spec.ts
apps/bb-score/src/app/core/services/sw-update.service.ts

- Updated `SwUpdateService` to provide statuses and maintain whether toast is visible or not
- Updated `UpdateToastComponent`
- Moved check from init to computed signal
- Added display of different statuses

fix(bb-score): make update toast show for new updates

---

apps/bb-score/src/app/games/game-list/game-list.component.html
apps/bb-score/src/app/games/game-score/game-score-manage.component.html
apps/bb-score/src/app/games/game-score/game-score-manage.component.scss
apps/bb-score/src/app/games/game-score/game-score-manage.component.ts
apps/bb-score/src/app/games/game.service.ts
apps/bb-score/src/app/games/lineup-edit/lineup-edit.component.html
apps/bb-score/src/app/games/lineup-edit/lineup-edit.component.ts
apps/bb-score/src/app/games/lineup-edit/lineup.service.spec.ts
apps/bb-score/src/app/games/lineup-edit/lineup.service.ts
apps/bb-score/src/app/games/lineup-edit/player-select/player-select.component.html
apps/bb-score/src/app/games/lineup-edit/player-select/player-select.component.ts
apps/bb-score/src/app/games/models/game.ts

- Updated label for button to open game details
- Updated `GameScoreManageComponent` to display lineup in an expansion panel.
- Updated the lineup panel to display warnings when starters are incomplete.
- Updated `GameService` to ensure `selectedGame$` always emits latest game details
- Updated lineup editing to save on value change without showing toast
- Updated `LineupService` to record player Ids in use in the lineup
- Updated `LineupService` to drive values from current game, and added `playerIdUsed$` to provide players currently used in lineup
- Streamlined player filtering logic by introducing a separate form group for player search. Improved handling of lineup form initialization and updates to reduce redundant event emissions. Added validation to disable already selected players …

feat(bb-score): disable players already in lineup

---

apps/bb-score/src/app/games/game-card/game-card.component.ts
apps/bb-score/src/app/games/game-create/game-create.component.spec.ts
apps/bb-score/src/app/games/game-create/game-create.component.ts
apps/bb-score/src/app/games/game-list/game-list.component.html
apps/bb-score/src/app/games/game-list/game-list.component.spec.ts
apps/bb-score/src/app/games/game-list/game-list.component.ts
apps/bb-score/src/app/games/game-score/scoring/scoring.service.spec.ts
apps/bb-score/src/app/games/game.service.spec.ts
apps/bb-score/src/app/games/game.service.ts
apps/bb-score/src/app/games/lineup-edit/lineup.service.spec.ts
apps/bb-score/src/app/games/models/game.ts
apps/bb-score/src/app/teams/models/player.ts
apps/bb-score/src/app/teams/models/team-summary.ts
apps/bb-score/src/app/teams/player-edit/player-edit.component.ts
apps/bb-score/src/app/teams/team-detail/team-detail.component.ts
apps/bb-score/src/app/teams/team.service.spec.ts
apps/bb-score/src/app/teams/team.service.ts
apps/bb-score/src/app/teams/teams-list/teams-list.component.ts

- Updated game selection logic in GameService to be driven by selected ID
- Replaced `getTeams` with `getTeamSummaries` for better abstraction of team summaries. Refactored selected team logic to use `teamId` and streamlined team addition, updates, and deletions. Updated dependent components and tests to align with these changes.
- Removed `league` from team, player, and game

fix(bb-score): ensure away team loaded for lineup edit
